# encoding: UTF-8

# puts "CREATE USERS"
# 20.times do
#   random_uid = rand(300000..302715)
#   User.create(
#     name: "#{Faker::Name.first_name} #{Faker::Name.last_name}",
#     email: Faker::Internet.email,
#     password: "password",
#     description: Faker::Lorem.paragraph
#   )
# end

User.create({
  name: "Jamil Abreu",
  email: "abreu.jamil@gmail.com",
  password: "1111111",
  admin: true},
  without_protection: true
)

User.create({
  name: "Dorisol Inoa",
  email: "dinoa@wesleyan.edu",
  password: "password",
  admin: true},
  without_protection: true
)

puts "CREATE 2013 EVENTS"
Event.create!(name: "Registration", venue: "Beckham Hall", start_time: DateTime.new(2013,3,29,18), end_time: DateTime.new(2013,3,29,23))
comedy_show = Event.create!(name: "Dominican Comedy Show", venue: "Usdan", start_time: DateTime.new(2013,3,29,20), end_time: DateTime.new(2013,3,29,22), show_in_program: true)
comedy_show.speakers.create!(first_name: "Vladimir", last_name: "Caamano", description: "With the name “Vladimir,” few
	people expect a Dominican from the Bronx to take the stage. In his own words, “My name is Vladimir,
	but I look more like Hector.” His experience is the fruit of an immigrant Dominican family living
	in the cultural mecca that is New York City. Raised in the Bronx and Washington Heights, Vladimir
	began polishing his wit while attending Wesleyan University. Whether discussing his grandfather
	who fathered 47 kids, going to college without luggage, or calling a cab company run by latino
	spies, you will enjoy watching this comedian weave a hilarious fabric of truth and absurdity.
	Check him out on http://www.laughingvlad.com.", image: "http://www.comedysoapbox.com/img/comedians/14801.jpg")

Event.create!(name: "Breakfast", venue: "Usdan", start_time: DateTime.new(2013,3,30,8), end_time: DateTime.new(2013,3,30,8,45))
Event.create!(name: "Registration", venue: "Beckham Hall", start_time: DateTime.new(2013,3,30,8), end_time: DateTime.new(2013,3,30,10))
Event.create!(name: "Welcome", venue: "Memorial Chapel", start_time: DateTime.new(2013,3,30,9), end_time: DateTime.new(2013,3,30,9,20))
dss = Event.create!(name: "Dominican Success Stories", venue: "Memorial Chapel", start_time: DateTime.new(2013,3,30,9,30), end_time: DateTime.new(2013,3,30,11,30),
	description: "Dominicans are a resilient people, shaped by our history, our diaspora, our sense of community. Join us
in an expose of Dominicans whose stories will inspire our own success stories. In line with the theme of
this year's conference, we hope to explore how individual success can be a medium for social justice by
changing the landscape of the cultural identities that are represented in different industries. Panelists
will also discuss if and how assimilation has played a role in their success. This workshop will be
moderated to include an in depth and collaborative discussion from student attendees.", show_in_program: true)
Event.create!(name: "Lunch", venue: "Backham Hall", start_time: DateTime.new(2013,3,30,11,45), end_time: DateTime.new(2013,3,30,1,15))
Event.create!(name: "Mami Echate Pa ‘Ka: The Hyper-sexualization of Women", venue: "CFA Hall", start_time: DateTime.new(2013,3,30,13,30), end_time: DateTime.new(2013,3,30,15),
	description: "Whether you live in Santo Domingo, Washington Heights or Lawrence, Massachusetts, as a woman of color, it is very likely that you know what it's like to be hollered at or piropia' on the street. In this workshop we will be discussing male and female interactions within our community. We will leverage our personal experiences and use media to analyze the ways in which we allow our gender to impact how we relate to one another. This discussion will be give a true taste of what class is like at Wesleyan, facilitated by one of our most radical professors, Bob Steele. Come prepared to let your voice be heard in rich discussion as you share your thoughts, experiences and personal opinions.", show_in_program: true)
Event.create!(name: "The Truth Behind Bars: The Prison Industrial Complex", venue: "Crowell Concert Hall", start_time: DateTime.new(2013,3,30,13,30), end_time: DateTime.new(2013,3,30,15),
	description: "Have you noticed a shortage of Dominican men and men of color, in general, in your classrooms? This discussion will address one of the probable causes of the under-representation of Black and Latino men in education: the prison industrial complex. With different panelists representing academia, prison policy, reform movements, and the prison and deportation experience, we aim to explore all perspectives of this problem. Topics discussed will include the war on drugs, stop and frisk, and the privatization of the prison system. This discussion will have you at the edge of your seat as you learn about the gravity of this situation.", show_in_program: true)
Event.create!(name: "Breakout Sessions", venue: "Various", start_time: DateTime.new(2013,3,30,15,30), end_time: DateTime.new(2013,3,30,16,30),
	description: "In this conference, we have allotted an hour for different student or professional organizations to propose and present a workshop on a social justice topic of their interest. Workshops will include: Transforming Community: Education, Leadership, Service (Avanzando Nuestra Comunidad a Travez de la Educacion) with Teach for America, City Year and the Peace Corps; Decolonizing Our Minds- A discussion on Internalized Oppression; Students Making Change- Dreamer Movement and Immigration Reform; and a workshop about current events in DR. To submit a proposal email us at wesndsc@gmail.com.", show_in_program: true)
Event.create!(name: "E Pa'lante Que Vamos, Recordando Nuestras Raíces: Organization Fair", venue: "Exley Lobbey", start_time: DateTime.new(2013,3,30,17), end_time: DateTime.new(2013,3,30,20),
	description: "This will be an organization fair which will include over ten organizations that are working to provide solutions to the social justice issues discussed during the conference. This will be your chance to participate in career-advancing networking and learn about volunteer opportunities to make a difference now! Confirmed organizations include but are not limited to Teach for America, City Year, the Peace Corps, Dominicans on Wall Street, the Society for Hispanic Professional Engineers, The National Latina Institute for Reproductive Health, Dominican York Proyecto Grafica and more. This fair will occur concurrently with our formal dinner, to give participants ample room and time to network. Conference participants will be assigned to one of two groups to attend dinner, alternating between dinner and the fair.", show_in_program: true)
Event.create!(name: "Group A: Dinner and Entertainment", venue: "Beckham Hall", start_time: DateTime.new(2013,3,30,17), end_time: DateTime.new(2013,3,30,18,15))
Event.create!(name: "Group B: Dinner and Entertainment", venue: "Beckham Hall", start_time: DateTime.new(2013,3,30,18,30), end_time: DateTime.new(2013,3,30,20))
Event.create!(name: "Keynote Speaker", venue: "Chapel", start_time: DateTime.new(2013,3,30,20,15), end_time: DateTime.new(2013,3,30,21,15))
Event.create!(name: "Party: Con Lo Pie", venue: "Beckham Hall", start_time: DateTime.new(2013,3,30,22), end_time: DateTime.new(2013,3,31,2))

Event.create!(name: "Breakfast", venue: "TBD", start_time: DateTime.new(2013,3,31,9), end_time: DateTime.new(2013,3,31,11))
Event.create!(name: "Closing Remarks", venue: "Beckham Hall", start_time: DateTime.new(2013,3,31,10,30), end_time: DateTime.new(2013,3,31,11))


dss.speakers.create!(first_name: "Angela", last_name: "Fernandez", suffix: "Esq.", description: "Currently serving as the Executive
	Director for Northern Manhattan’s Coalition for Immigrant Rights, Angela is a a graduate of
	Columbia University School of Law who has 20 years professional experience in law, media,
	non-profit management, government, policy development and advocacy. Her public interest law
	experience includes working with the Center for Human Rights Legal Aid in Cairo, Egypt and
	providing pro bono legal services through the American Immigration Lawyers Association. Ms.
	Fernandez has also successfully founded and managed elementary schools in the South Bronx
	and in Washington DC, was a Women's Studies instructor for the LCC Inmate Education
	Program at Riker's Island and was a staffer for former United States Senator Bill Bradley.",
	image: "http://www.nmcir.org/AF.JPG")
dss.speakers.create!(first_name:"Sonia", last_name: "Manjon", suffix: "Ph.D", description:"Sonia BasSheva Mañjon is Vice President for Institutional Partnerships
and Chief Diversity Officer of Wesleyan University. In this role, Dr. Mañjon
provides leadership in community collaborations, institutional partnerships
and civic engagement activities. Dr. Mañjon also advises the Connecticut
Parent Union, serves on the leadership council of the Middlesex County
Coalition on Housing and Homelessness, is a board member for the
Middlesex Chamber of Commerce, and is a State Commissioner for Latino
and Puerto Rican Affairs. Dr. Mañjon has more than 25 years of experience
in higher education, nonprofit, and government administration. Dr. Mañjon is a sought after
public speaker on a wide variety of topics, including community collaborations, arts integrated
education, cultural arts, identity, and intergenerational immigration issues. She has presented
research on marginalized and invisible immigrant communities at national and international
conferences including the First Annual Women of Color, Mixed Heritage, Ethnicity, and Race
Conference in Texas and the 2006 International Conference on the Arts in Society held in
conjunction with the Edinburgh Arts Festival in Scotland. Dr. Mañjon earned a Ph.D. in
Humanities and a Master of Arts in Cultural Anthropology from the California Institute of
Integral Studies, San Francisco. She received a Bachelor of Arts in World Arts and Cultures
from the University of California, Los Angeles.", image: "http://www.middletownpress.com/content/articles/2011/01/17/news/doc4d34bafc6ce156041056213.jpg")

# puts "CREATE 2012 EVENTS"
Event.create!(name: "Registration", venue: "Third World Center", start_time: DateTime.new(2012,4,6,15), end_time: DateTime.new(2012,4,6,21))
Event.create!(name: "Networking w/ Alumni, Students and Staff", venue: "Sayles Hall", start_time: DateTime.new(2012,4,6,18), end_time: DateTime.new(2012,4,6,19))
Event.create!(name: "Ice Breakers & Screening of 'Sugar'", venue: "MacMillan 117", start_time: DateTime.new(2012,4,6,19), end_time: DateTime.new(2012,4,6,22))
Event.create!(name: "Private Cocktail (hosted by Phi Kappa Psi)", venue: "Phi Kappa Psi", start_time: DateTime.new(2012,4,6,22), end_time: DateTime.new(2012,4,7,2))

Event.create!(name: "Registration & Breakfast", venue: "Andrews Hall", start_time: DateTime.new(2012,4,7,8), end_time: DateTime.new(2012,4,7,10))
Event.create!(name: "Welcome Address", venue: "Salomon 101 / DECI", start_time: DateTime.new(2012,4,7,10), end_time: DateTime.new(2012,4,7,10,30))
brown_amarillo = Event.create!(name: "El Movimiento Amarillo: Our Community, Our Education", venue: "Salomon 101 / DECI", start_time: DateTime.new(2012,4,7,10,30), end_time: DateTime.new(2012,4,7,12,30), description: "In addressing the Dominican-American student experience, this workshop will ask panelists and participants to consider the experience and issues surrounding Dominican students in the United States. We are well aware of some issues - like retention and graduation rates. Panelists from different areas will discuss these and other issues that not only Dominican-Americans, but Hispanic-Americans face altogether. With these discussions, we hope to give our audience an opportunity to see their own experiences reflected, shared, and expanded upon.")

Event.create!(name: "Lunch & Networking ", venue: "Kasper Multipurpose Room", start_time: DateTime.new(2012,4,7,12,30), end_time: DateTime.new(2012,4,7,14))

Event.create!(name: "Con Merengue y Con Bachata: An International Spread", venue: "Salomon 001", start_time: DateTime.new(2012,4,7,14,1), end_time: DateTime.new(2012,4,7,15,15), session: true, description: 'Music is the soul of the Dominican people. Its influence is so strong that very often we use the phrase "Dominicano hasta la tambora" to identify ourselves. Traditionally, our music has targeted a primarily Dominican audience. In recent decades, the mass migration of Dominicans to the United States has prompted our music to adapt to this emerging bi-national identity. The goal of this workshop is to learn about the impact of globalization on Dominican music from those who are well informed on this phenomenon, and to further examine the importance of this popularized force to help in the struggle for a better Dominican Republic. To open the workshop, a compilation of clips about musical styles, rhythms, dances, instruments, and popular artists will be shown to understand the international popularization of Dominican music. After this brief presentation, an open discussion on Dominican music and its evolving nature both in the Dominican Republic and here in the United States will take place among invited panelists and participants.')
Event.create!(name: "Dios, Patria y Libertad: Communities Divided", venue: "Salomon 101 / DECI", start_time: DateTime.new(2012,4,7,14), end_time: DateTime.new(2012,4,7,15,15), session: true, description: "The force of the religious community in the Dominican Republic has had a strong impact on the nation's life and identity. The common expectations, teachings, and practices of popular religious groups have been important to Dominican development at home and abroad. At the root of this religious unity lies a strong lack of acceptance for images that differ from traditional gender roles. LGBTQ life is rarely, if ever, discussed in a religious context. As in many Latin American countries, homophobia and hyper-masculinity remain pervasive throughout much of the Dominican Republic.To introduce this workshop a series of images and text will be shown to participants and later this will transition to a personal and confidential group discussion in order to make us cognizant of the issues faced by Dominicans who are members of the LGBTQ community.")
Event.create!(name: "Special Event: Dominicans in Politics - An Open Panel to Brown and RI Community", venue: "Salomon 101 / DECI", start_time: DateTime.new(2012,4,7,15,30), end_time: DateTime.new(2012,4,7,17), description: "The past twenty years have been critical for the progress of the Dominican-American profile in government and politics. Beginning with the first Dominican-American to be elected as city council member in 1991 to the election of Juan Pichardo to the Rhode Island State Senate, Dominicans have definitely made strides in politics. Angel Taveras became the first Hispanic mayor of Providence, Rhode Island, a city with a considerable Dominican population. This was an important breakthrough for Dominicans in American politics. With a growing population of people of Dominican descent who need political representation, Dominican accomplishments in American politics are becoming ever more important. Through this workshop, conference attendees will be able to discuss various issues pertinent to Dominican-American politics with the politicians themselves. We are presently waiting to hear from other special guests that have been invited to participate in this panel that promises to be very interesting.")
Event.create!(name: "Dominican Entrepreneurship: Beyond the Bodega", venue: "Salomon 101 / DECI", start_time: DateTime.new(2012,4,7,17), end_time: DateTime.new(2012,4,7,18,15), session: true, description: "Dominicans are known to be active in commerce, but the general perception is that they are only involved in bodegas. These bodegas generate economic activity that benefit the community as well as provide a platform where community members can interact and socialize. This workshop seeks to bring up the discussion about the significance of the bodega in the United States as well as its roots grounded in the Dominican Republic. Furthermore, the workshop will explore the role of Dominican Entrepreneurs who have branched out to other type of businesses that have equal or greater economic impact in our communities.")
Event.create!(name: "An 'Accent' on Identity - Language Discrimination", venue: "Salomon 001", start_time: DateTime.new(2012,4,7,17,1), end_time: DateTime.new(2012,4,7,18,15), session: true, description: "Many regions in the Dominican Republic speak different dialects of Spanish. Dominicans from rural areas are usually denoted as uneducated due to the way they pronounce certain words. Different dialects of Spanish can be perceived as having more positive or negative educational and socio-economic connotations. By discussing the issue of dialect discrimination with authors and published scholars we can raise awareness about this issue not only in the Dominican Republic, but also in the United States. Workshop participants will be encouraged to consider questions about the differences between European Spanish, Caribbean Spanish and Central/South American Spanish and how they affect the way Latinos communicate and interact.")

Event.create!(name: "Dinner Event", venue: "Andrews Hall", start_time: DateTime.new(2012,4,7,19), end_time: DateTime.new(2012,4,7,20,45))
Event.create!(name: "Keynote Address", venue: "Salomon 101 / DECI", start_time: DateTime.new(2012,4,7,21), end_time: DateTime.new(2012,4,7,21,45))
Event.create!(name: "Party", venue: "Andrews Hall", start_time: DateTime.new(2012,4,7,22,30), end_time: DateTime.new(2012,4,7,2))

Event.create!(name: "Mangu Breakfast", venue: "Andrews Hall", start_time: DateTime.new(2012,4,8,10), end_time: DateTime.new(2012,4,8,12))
Event.create!(name: "Closing Remarks", venue: "Andrews Hall", start_time: DateTime.new(2012,4,8,12), end_time: DateTime.new(2012,4,8,13))

puts "CREATE 2012 SPEAKERS"
# Speaker.create!(name: "Junot Díaz", description: "Junot Díaz was born in Santo Domingo, Dominican Republic and is the author of Drown and The Brief Wondrous Life of Oscar Wao which won the John Sargent Sr. First Novel Prize, the National Book Critics Circle Award, the Anisfield-Wolf Book Award, the Dayton Literary Peace Prize and the 2008 Pulitzer Prize. His fiction has appeared in The New Yorker, African Voices, Best American Short Stories (1996, 1997, 1999, 2000), in Pushcart Prize XXII and in The O'Henry Prize Stories 2009. He has received a Eugene McDermott Award, a fellowship from the John Simon Guggenheim Memorial Foundation, a Lila Acheson Wallace Readers Digest Award, the 2002 Pen/Malamud Award, the 2003 US-Japan Creative Artist Fellowship from the National Endowment for the Arts, a fellowship at the Radcliffe Institute for Advanced Study at Harvard University and the Rome Prize from the American Academy of Arts and Letters. He is the fiction editor at the Boston Review and the Rudge (1948) and Nancy Allen professor at the Massachusetts Institute of Technology.",
# image: "brown/speakers/Junot-Diaz.jpeg", keynote: true)

brown_amarillo.speakers.create!(first_name: "Marco Antonio", last_name: "Davis",
	description: "Marco Antonio Davis is the deputy director of the White House Initiative on Educational Excellence for Hispanics. Named to his post on Jan. 30, 2012, he helps carry out President Obama's efforts to improve the academic achievement of the nation's Hispanic students. Prior to joining the initiative, Davis served as the director of public engagement for the Corporation for National and Community Service, leading President Obama's call to service initiative, United We Serve, and the annual MLK National Day of Service and September 11 National Day of Service and Remembrance. The son of a Jamaican father and a Mexican mother, Davis and his two older sisters grew up in Mount Vernon, N.Y. He attended public and private schools before enrolling at Yale University. After he earned his bachelor's degree in history and Latin American studies in 1992, his first job took him back to New York, where he worked as a academic counselor at the innovative Prep for Prep program, which identifies outstanding students of color from modest backgrounds and connects them with private high schools and, later, prestigious colleges.",
	image: "brown/speakers/Marco-Davis.jpg")
brown_amarillo.speakers.create!(title: "Dr.", first_name: "Erik E.", last_name: "Morales", suffix: "Ph.D", description: 'Dr. Erik E. Morales is currently an Associate Professor in the Department of Elementary & Secondary Education at New Jersey City University. He received his B.S. in English Education and his Ph.D. in Higher Education from New York University, as well as his M.Ed. in Education Administration from William Paterson University. He has published more than fifteen articles in scholarly journals, including "Legitimizing hope: An Exploration of Mentoring for Dominican American Male College Students, Journal of College Student Retention: Research, Theory, & Practice, Vol. 11(3), 385- 406 and "Academic Resilience in Retrospect: Following up a Decade Later, Journal of Hispanic Higher Education, 7(3), 228-248; as well as two books on academic resilience: Promoting Academic Resilience in Multicultural America (Peter Lang Press, 2004), and A Focus on Hope: Fifty Resilient Students Speak (University Press of America, 2011). He has presented at a multitude of conferences and professional development gatherings nationwide.',
image: "brown/speakers/Erik-Morales.jpg")
brown_amarillo.speakers.create!(first_name: "Amaris", last_name: "Guzman", description: "Amaris Del Carmen Guzman is a second-generation Dominicana native from Paterson, NJ whose parents were born in Santiago, Dominican Republic. As an undergraduate at St. John's University, Amaris became president and co-founder of the Latino American Student Organization (LASO) and continued her involvement as a LASO Alumni Advisor in the subsequent years. In 2007, Amaris received a B.S. in Criminal Justice from St. John's and served as the Graduate Student Marshal upon graduating with a M.A. in Latin American and Border Studies from the University of Texas at El Paso in 2009. At the age of 24, she began her Ph.D. work in Caribbean Studies at the University at Albany in upstate New York. Now in her second year of doctoral work, her research seeks to recover the narratives of Caribbean student leaders during the 1960s who paved the way for our generation to flourish. Amaris currently serves as the youngest serving Board Member of the Dominican American National Roundtable. She is also an active and proud hermana of the Gamma Eta Graduate Alumnae Chapter of Hermanidad de Sigma Iota Alpha, Inc. As an intellectual activist, Amaris hopes to serve as an encouragement tool for her younger peers to pursue graduate school and doctoral work in the near future.",
image: "brown/speakers/Amaris-Guzman.jpg")
brown_amarillo.speakers.create!(first_name: "Chrismaldi", last_name:"Vasquez", description: "Chrismaldi Vasquez currently leads the education strategy and initiatives for Boston Rising, a start up foundation focused on eliminating poverty. Previously, she was Director of Community Impact with the United Way of Massachusetts Bay and Merrimack Valley. She served as a relationship manager for youth serving agencies and external partners. She was also a project manager for several initiatives that focused on increasing youth opportunities and civic engagement. Most recently, she was the Manager of Organizing and Policy Initiatives. In this role, she was responsible for two youth community development teams and several organizing and policy campaigns. She has developed a national reputation for her leadership in several grassroots youth community organizing campaigns including defeating a plan for a K-Mart in Jackson Square and fighting sexual harassment on Boston's streets and in the public schools. She also led the successful effort for a new Civics curriculum in the Boston Public Schools. Many of the organizing campaigns that she has led have received national media attention and they have been featured in youth development journals and academic books. In recent years, she traveled throughout the country to lead workshops for other youth organizing groups, conferences and colleges. Chrismaldi graduated from Bentley University with a B. S in Economics and Finance with a minor in International Studies.",
image: "brown/speakers/Chrismaldi-Vasquez.jpg")
brown_amarillo.speakers.create!(first_name: "John", last_name:"Moreno-Escobar", description: "John Moreno-Escobar founded his own non-profit organization (Latino Youth for Higher Education Program) in order to educate and assist newcomer Latino students and families in the process of applying, preparing and paying for higher education in the United States. He is naturally from Bogota, Colombia, but migrated 9 years ago to further his studies. In 2010 he graduated from Baruch College in Public Affairs with a minor in Latin American Studies and the Caribbean. He is currently pursuing his Masters in Public Administration at the School of Public Affairs - Baruch College. John was recently appointed as Partnerships Manager in the NY Region for New Futuro. This National Educational organization has created an educational community that helps Latino families get their students into college and beyond. Through a completely free, bilingual, 'high- tech, high-touch' experience, New Futuro connects those that need help with those that provide it. New Futuro uses digital, media and neighborhood outreach efforts and partners with schools, not-for- profits and community based organizations to help them expand their reach. As a Partnerships Manager for the New York Region, he is responsible to create healthy and strong relationships, with major stake holders and share all the New Futuro resources with the Latino Community.",
image: "brown/speakers/John-Moreno-Escobar.png")
brown_amarillo.speakers.create!(first_name: "Anthony", last_name:"Stevens-Acevedo", description: "Anthony Stevens-Acevedo is assistant director and founding member of the Dominican Studies Institute of the City University of New York (CUNY DSI) at The City College of New York. He is a founding member of the Council of Dominican Educators, the Dominican Studies Association, and a Foreign Corresponding Member of the Dominican Academy of History (Dominican Republic). Stevens-Acevedo is a historian and focuses his research on the early colonial history of the Dominican Republic. He is the lead investigator in CUNY DSI's Dominican colonial research projects. Prior to joining CUNY DSI, Stevens-Acevedo taught Social Studies for more than a decade at Theodore Roosevelt High School and Gregorio Luperon High School, both in New York City. He has a long history of community activism in Washington Heights, the best-known hub of the Dominican community in New York City. Stevens-Acevedo has an M.A. in History from The City College of New York, CUNY, and a B.A. in History of the Americas from the University of Seville, Spain.",
image: "brown/speakers/Anthony-Stevens-Acevedo.jpg")

# Speaker.create!(name: "Carlos Pichardo", description: "Carlos Pichardo was born in the Dominican Republic. He is currently incubating a Healthcare HR outsourcing start up at the Bronx Business Incubator. The concept behind this venture is to not only create a niche product in the growing field of HR outsourcing, but also help physicians build integrated networks where care coordination can be carried out seamlessly. Carlos has served as an activist for various causes in the past, the latest being the 4% movement in the Dominican Republic. He is a firm believer in the link between greater prosperity in developing countries and robust investment in Research and Development. For this purpose, he is in the process of co-founding a non-profit organization that seeks to help Universities in low-income countries build endowment funds by channeling the energy of diasporic communities and by enabling the type of links that can foster greater innovation between institutions of higher learning. Carlos holds a B.A. from Columbia University.",
# image: "brown/speakers/Carlos-Pichardo.jpg")
# Speaker.create!(name: "Ico Abreu, M. Arch.", description: "A Fulbright Fellow currently pursuing his second master degree at the University of Cincinnati. Besides his professional practice, Ico has developed an academic career at the School of Architecture of Pontificia Universidad Catolica Madre y Maestra (PUCMM), where for the last five years he has taught both in undergraduate and graduate schools. In 2011 he was awarded Meritorious Professor of PUCMM. Ico has been Guest Professor at national and international workshops. Among other congresses, he has represented the Dominican Republic at the Young Architects World Forum. He has been a speaker at a variety of prominent academic Dominican and international conferences such as the Latin American Conference of Schools and Faculty of Architecture (CLEFA) in Buenos Aires. As an activist, Ico has been involved in manifestations for environmental and social causes, such as the advocacy for the defense of the Dominican system of protected areas. He led the team that coordinated Música Por Los Haitíses, and is part of the coordination team of Coalición Educación Digna (Coalition for a Worthy Education).",
# image: "brown/speakers/Ico-Abreu.jpg")
# Speaker.create!(name: "Paola Martinez", description: "Paola Martinez is a Dominican-born, fierce activist of education and immigrants’ rights. She has led the efforts of La Coalicion Educacion Digna in the US to strengthen the advocacy for the allocation of 4% of the GDP for public education, mandated by the constitutional law 66-97 in Dominican Republic. Paola is currently a Community Mobilization & Advocacy Fellow with La Fuente, an organization that works for the rights of immigrant’s and workers in underserved communities throughout New York City. Further, she coordinates the Votos y Voces campaign, an initiative to mobilize new and inactive voters, and engage them to influence the election’s decision-making process. Formerly, she was an intern for the Community Mobilization Department of the National Latina Institute for Reproductive Health (NLIRH) and Education & Advocacy Fellow of the Dominican American National Round Table (DANR). While pursuing a career in Political Science, concentrating in law and policy at Baruch College, she works as a Spanish teacher at the Dalton School in New York City and the Instituto Cervantes, the leading institution that promotes the Spanish language and Spanish & Hispanic-American culture around the world. Through her job she develops her passion for languages, education, and involvement with children.",
# image: "brown/speakers/Paola-Martinez.jpg")
# Speaker.create!(name: "Ramona E. Romero", description: "As the General Counsel of the United States Department of Agriculture, Ramona Emilia Romero is the principal legal advisor to Secretary Tom Vilsack and other Department officials. President Obama nominated her on June 28, 2010 and she was confirmed unanimously by the United States Senate on December 22, 2010. Ms. Romero serves as the Chief Legal Officer of the USDA and oversees the work of about 300 legal professionals who provide legal advice and support to all components of the Department. Before joining the Administration, Ms. Romero was a Corporate Counsel at E.I. du Pont de Nemours and Company (DuPont), where she provided legal oversight for the acquisition of transportation, distribution, supply-chain management, travel and energy resources, and managed related strategic litigation. From 2008 through 2010, Ms. Romero also served as General Counsel of Sentinel Transportation LLC, a DuPont joint venture. She also held other key positions at DuPont, including Corporate Counsel for complex commercial and antitrust litigation, and Corporate Counsel and Manager of Operations and Partnering. While at DuPont, Ms. Romero led various initiatives aimed at promoting diversity in the legal profession and was a frequent public speaker on that subject. During the first ten years of her legal career, Ms. Romero was a litigator at Crowell and Moring in Washington, DC where she handled a broad range of commercial, government contract and white collar matters. Ms. Romero, who immigrated to the United States from the Dominican Republic at age 10, holds a B.A. from Barnard College and a J.D. from Harvard Law School.",
# image: "brown/speakers/Ramona-Romero.jpg")
# Speaker.create!(name: "Yoseli Castillo", description: "Yoseli Castillo Fuertes was born in the Dominican Republic in 1972, and at the age of 16 migrated to the United States. She holds a BA in Psychology and an MA in Spanish Literature. Her poems and short stories have appeared in Desobedientes. Experiencias y reflexiones sobre poliamor, relaciones abiertas y sexo casual entre lesbianas, Buenos Aires, 2009; MundoLavapies, Madrid, 2006; Divagaciones bajo la luna/ Musing under the Moon, Santo Domingo, 2006, and Encuentro: 10 poetas latinoamericanos en USA, New York, 2003. She is a bilingual-Dominican-Latina-lesbian poet-activist-teacher-aunt. Her activism started in 1994 when she helped found The Barbara Witenko Women Center at Long Island University (Brooklyn). A few years later she participated in Alianza Dominican’s Project Encounter and was a member of Las Hijas de la Luna, NYC’s first Dominican lesbian group. Since 2003 she has been part of GALDE’s Board of Directors and since 2004 has served as its Vice Chair. Currently she is the Chair. For more than 5 years she has organized the Gay & Lesbian Bohemian Night in Washington Heights. She has participated or collaborated with organizations such as Las Buenas Amigas, Queens Pride House, PRIDE, Mateando, SAGE, The Audre Lorde Project, The Center, amongst others. Her first poetry book De eso sí se habla/Of That, I speak New York, 2012 is now on sale.",
# image: "brown/speakers/Yoseli-Castillo.jpg")
# Speaker.create!(name: "Alicia Anabel Santos", description: "Alicia Anabel Santos is a Latina Writer, Producer and Playwright. She is a New York-born Dominican who is passionate about writing works that empower and inspire women to find their voices. She recently published her memoir, Finding Your Force: A Journey to Love and is currently completing a historical fiction novel titled, The Daughters of the Revolution. Her one-woman show I WAS BORN was selected as part of the ONE Festival in 2011, held in NYC. She is the Founder of the NYC Latina Writers Group. Alicia has worked for renowned magazines BusinessWeek, Glamour and Domino, but it was an article published in Urban Latino Magazine, 'Two Cultures Marching to One Drum' that would change the direction of her life. In 2008, Alicia joined Creador Pictures as Writer /Co-Producer of its first documentary, 'Afro Latinos: La Historia Que Nunca Nos Contaron / AfroLatinos: The Untaught Story' WWW.AFROLATINOS.TV, partnering with Renzo Devia, on a project that will change the way the world sees color and race relations in Latin America. Alicia lives in Harlem, NYC with her daughter Courtniana. She works as a freelance writer and activist against sexual and physical abuse towards women and children. She attended New York University and Rhode Island College.",
# image: "brown/speakers/Alicia-Anabel-Santos.jpg")
# Speaker.create!(name: "Francisco J. Lazala", description: "Francisco J. Lazala was born in the Dominican Republic and came to the US in 1985. He earned his BA in Sociology from Lehman College in 1996 and earned one year towards his Masters in Non-Profit Management from the New School University in 1999. Francisco (Cisco) is currently the Director of Programs at the Bronx Community Pride Center (BCPC); previously, he worked as the Outreach Coordinator for BCPC. He has worked for New York Harm Reduction Educators as the Coordinator of Structured Interventions and Integrated. He served as director for: the Mpowerment Program, an HIV prevention program targeting gay & bi men; the SOMOS Program, a citywide anti-homophobia project; Crystal Meth Initiative Program; and Mano a Mano Program, a capacity building program targeting gay Latino grassroots organizations, all at the Latino Commission on AIDS. Cisco also worked as program coordinator for outreach & education and LGBT services at Alianza Dominicana and at the Young Adults Against Drugs & Alcohol in the Bronx. Cisco is the Chair & Founder of the Gay and Lesbian Dominican Empowerment Organization, Inc., serves on the Advisory Board of Latinos Unidos of New York and on the board of the tenant association. Francisco coordinates the biggest LGBT Dominican Picnic / Health Fair in the US for the last 16 years. He also served as consultant for BCPC, Columbia University, & Amigos Siempre Amigos.",
# image: "brown/speakers/Francisco-Lazala.jpg")
# Speaker.create!(name: "Carlos Rodriguez", description: "Carlos Rodriguez is an activist, filmmaker and photographer who tells stories about LGBTQ people and works every day to render visible the Dominican community in it’s richness and complexity. He is one of the co-founders of IURA (Individuals United for Respect and Harmony), an organization that focuses on LGBTQ Legal Rights in Santo Domingo. His participation in the recent documentary film ¨Afuera Hay Aire¨ documents the lives of numerous members of the LGBTQ community and their daily experiences across various parts of the Dominican Republic. His work has been recently screened at New England Festival of Ibero American Cinema and NYC Caribbean Queer Film Festival, among others. Website: www.carlosr.co",
# image: "brown/speakers/Carlos-Rodriguez.jpg")



# Speaker.create!(name: "Deyanira 'Sargenta G' Garcia", description: "A Dominican Lesbian author, performer, lyricist, and activist whose mission is to “Express freely without shame or guilt the social issues affecting our community.” She uses the power of words and music to promote educational activism. Sargenta G has participated and performed in various underground events including in various colleges and community locations. Garcia is the author of Gritando En Silencio, a poetry book that addresses the issues of Domestic Violence and leaves room for hope to break the cycle; this book was adapted for the stage by The Fantastic Experimental Latino Theater Inc. in 2009 and was presented as a play to bring awareness to the community. She has been featured in Univision, El Diario and the New York Daily News. She currently works as an Employment Specialist in the COPE Program at Hostos Community College/CUNY and lives in New York. Website: www.passionbeforefear.com",
# image: "brown/speakers/Deyanira-Garcia.jpeg")
# Speaker.create!(name: "Prof. Deborah Pacini Hernandez", description: "Deborah Pacini Hernandez is Professor of Anthropology and American Studies at Tufts University. Her research areas include comparative Latino studies; Latino community studies; ethnic and racial identity in Caribbean and U.S. Latino popular music and culture; and the impact of the globalization on Latin/o popular music. She is the author of Oye Como Va! Hybridity and Identity in Latin/o Popular Music, Temple University Press, 2010 and Bachata: A Social History of a Dominican Popular Music, Temple University Press, 1995. She is also co-editor of Reggaeton (with Raquel Rivera and Wayne Marshall), Duke University Press, 2009, and co-editor of Rockin’ Las Americas: The Global Politics of Rock in Latin/o America (with Eric Zolov and Hector Fernández L’Hoeste), University of Pittsburgh Press 2004.",
# image: "brown/speakers/Deborah-Pacini.jpg")
# Speaker.create!(name: "Sydney Hutchinson", description: "Sydney Hutchinson is assistant professor of ethnomusicology at Syracuse University. She is the author of an award-winning book on Mexican American dance and youth culture (From quebradita to duranguense, University of Arizona Press, 2007) and numerous articles on merengue típico, salsa, and ballet folklórico in journals including Ethnomusicology, Journal of American Folklore, Popular Music, and world of music. In addition, she co-produced and wrote liner notes for the Smithsonian Folkways CD La India Canela: Merengue típico from the Dominican Republic. Hutchinson is currently preparing a book on the performance of gender in Dominican music and editing a volume entitled Dancing in place: Global salsa in local contexts, forthcoming from Temple University Press. She has been researching merengue típico in New York and Santiago de los Caballeros since 2001 and also has been known to play típico accordion herself on occasion; she has been a student of Rafaelito Román since 2004.",
# image: "brown/speakers/Sydney-Hutchinson.jpg")
# Speaker.create!(name: "Marti Cuevas", description: "After spending 10 years as a working musician in Madrid, Spain, Marti Cuevas moved back to California and in 80s relocated to New York City with two small children in tow. Her dream was to play saxophone in the Big Apple, working part time to assuage the instability of a musical career. Marti landed a job with legendary music attorney, William Krasilovsky; this was her first brush with the music business. In 1991, Mr. Krasilovsky’s clients, J & N Records, eventually hired Marti to administrate their nascent company. Marti spent 10 exhausting years playing gigs on the merengue scene, while working full time for J & N. In 2003, Marti’s company Mayimba Music, Inc. signed on, as administrator for Premium Latin Music, Inc. Premium is best known for its stellar artist, Aventura. At present, she is developing her own company, while working with both Premium and J & N.",
# image: "brown/speakers/Marti-Cuevas.jpg")
# Speaker.create!(name: "Andres Salce", description: "With over 20 years of experience in the Latino Music Industry, Andres Salce has produced tours and concerts for top caliber artists such as, Enrique Iglesias, Ricardo Montaner, Franco De Vita, Olga Tañon, Alejandro Sanz, Frankie Negron, Elvis Crespo, Marco Antonio Solís, Ricardo Arjona, Camila, Reik, and Ednita Nazario. He was also responsible for the production of the, now mythical, sold-out concert of Luis Miguel in New York’s Madison Square Garden, in 2001, as well as Wisin & Yandel’s “La Revolucion Tour”. Andres also managed and produced several campaigns and concert tours for various acclaimed Latin artists such as; Aventura, Los Hermanos Rosario, Reyli Barba, Jennifer Lopez, Kat De Luna, Tito El Bambino, and Hector Acosta. In his beginnings, Salce worked at JN Records, where he collaborated with some of today’s biggest Latin music exponents and obtained a first-row seat to witness the birth of the explosive musical genres, Bachata and Reggaetón. After JN Records, Salce worked as a promotions executive for Latin Capitol EMI, and for Fonovisa in 1998. By the year 2000, Salce was working for Warner Latin Music, where he excelled at obtaining a greater mainstream presence for the record label’s artists. By 2002, Salce returned to EMI Latin Music, where he continued evolving in the promotions and artistic development areas; however, this time his responsibilities included a much greater participation, at corporate level, which led to becoming the head of UBO’s marketing and promotions personnel, and later Sony Music. After working at Universal Latin in 2004, Salce decided it was time to put his vast experience and entrepreneurial spirit into what is now, The Cerro Music Group, his own company. He now holds the title of Founder and CEO where he implements and oversees promotional campaigns for Sony BMG, Venemusic, Machete Music, and various other projects all over the world.",
# image: "brown/speakers/Andres-Salce.jpg")

# Speaker.create!(name: "Sen. Juan M. Pichardo", description: "Juan M. Pichardo arrived to the US from Jicome-Santiago, DR in 1975, and lived in NYC prior to moving to Providence in 1979. On 2003, Pichardo was sworn in as a State Senator representing the 2nd Senatorial district in the State of R.I. Pichardo serves as Senate Deputy Majority Leader and as a member of the Senate Committee on Finance, where he serves as Chairman of the Subcommittee on Human Services and Transportation. In addition, Sen. Pichardo also serves as Secretary of the Health and Human Services Committee. He holds an A.A. from the Community College of Rhode Island, an A.A.S in Audio Visual Production Services from the Community College of the Air Force, and has completed the Air National Guard NCO Academy on 2003. Pichardo joined the 143rd Military Security Force as a Security Police Specialist. By co-founding a non-profit organization, Quisqueya In Action, Senator Pichardo remains extremely active in the community. The organization works to maintain the Dominican-American cultural relationship and assists and promotes the pursuit of higher education among young people and families in the city of Providence. Senator Pichardo also co-founded the RI Latino Political Action Committee, of which he is the former Vice President. Senator Pichardo has the distinction of being named the first Latino elected to a R.I. Senate seat and the first Dominican-American elected to a State Senate seat in the US.",
# image: "brown/speakers/Juan-Pichardo.jpg")
# Speaker.create!(name: "Angel Taveras", description: "Angel Taveras is Providence's 37th Mayor. An attorney and former Providence Housing Court Judge, Mayor Taveras was elected as the city's first Latino mayor with 82 percent of the vote in November 2010.Mayor Taveras, 40, grew up on the South Side of Providence, where he attended Head Start before entering the Providence Public Schools, and went on to graduate with honors from Harvard University. Before pursuing his lifelong dream of becoming a lawyer, Mayor Taveras used a fellowship award to create an after-school program and summer day camp at the Elmwood Community Center. After obtaining his law degree from Georgetown University, Mayor Taveras returned to Providence to practice at the prestigious firm of Brown Rudnick LLP.In 2007, Mayor Taveras was appointed by then-Mayor David N. Cicilline to serve as an Associate Judge on the Providence Housing Court and was twice confirmed by the Providence City Council. During his tenure on the court, Mayor Taveras was instrumental in streamlining the interaction between Inspectors and the Housing Court and to improve the code enforcement tracking system.",
# image: "brown/speakers/Angel-Taveras.jpeg")
# Speaker.create!(name: "Ydanis Rodriguez", description: "Ydanis Rodriguez has a long track record of fighting and winning for the community he represents. For more than 20 years he has served his community with honesty, dignity, and integrity. As Council Member he continues to fight for much-needed services for Northern Manhattan, including immigration reform, higher quality education for all children, affordable housing and health care, and a more transparent and efficient government. Ydanis was born in the Dominican Republic and came to Washington Heights when he was 18 years old. He earned his Bachelor’s Degree in Political Science at the City College of New York, paying his way working as a taxi-driver. He then went on to obtain his Master’s degree in Bilingual Education at City College. In 1992, Ydanis successfully helped to found Gregorio Luperon High School, a school dedicated to the success of immigrant families, where he became a public high school teacher. Although Ydanis began his activism in the Dominican Republic fighting for a new school in his hometown, Licey Almedio, and continued during his tenure at City College, working to fight against tuition increases and budget cuts through student government, his 14 years of experience teaching refined and strengthened his passion for serving the community.",
# image: "brown/speakers/Ydanis-Rodriguez.jpg")
# Speaker.create!(name: "Grace Diaz", description: "After receiving 53 percent of the vote, Diaz became the first Dominican-American woman elected to state office in the history of the US, as State Representative. Diaz was appointed to the House Committee on Health, Education, Welfare, and Rules. She was also named to the Permanent Legislative Commission on Child Care. By the end of her first term, Diaz opened a neighborhood office for constituents and community groups and passed a bill to protect the civil rights of all Rhode Islanders by creating the Office of the Civil Rights Advocate in the Department of the Attorney General.Grace serves in the House Committee on Constituent Services and in the House Minority Caucus. Most recently, Diaz was appointed as vice chairwoman of the Rhode Island Democratic Party. She also became a superdelegate to the Democratic National Convention and is the first Latina-American to serve in such a high-ranking Democratic Party position. It is Representative Diaz's hope to continue working for social and economic justice.",
# image: "brown/speakers/Grace-Diaz.jpg")
# Speaker.create!(name: "Alejandra Castillo", description: "Ms. Alejandra Castillo is the National Deputy Director of the Minority Business Development Agency (MBDA). In this role, Ms. Castillo will serve as the principal advisor to the MBDA National Director and will assist in managing the day-to-day activities of the Agency. Prior to her appointment with MBDA, Ms. Castillo served as Special Advisor to the Under Secretary for the U.S. Department of Commerce’s International Trade Administration (ITA) where she was responsible for business outreach and development of policy initiatives geared at trade promotion and enforcement of U.S. trade laws. A practicing attorney for several years, Ms. Castillo has worked in the private, government and non-profit sector. Prior to joining the Obama Administration, Ms. Castillo served as the Interim Executive Director of the Hispanic National Bar Association headquartered in Washington D.C. During her tenure at HNBA, she was instrumental in working with the White House as well as non-profit organization, such as the Latinos for a Fair Judiciary, in support of the nomination and confirmation process to the Supreme Court of Justice Sonia Sotomayor. A native of New York, Ms. Castillo holds a Bachelor Degree of Arts from the State University of New York at Stony Brook in economics and political science. Ms. Castillo holds a Master’s degree in Public Policy from the Lyndon Baines Johnson School of Public Affairs, University of Texas at Austin and has a Juris Doctorate degree from American University (AU)-Washington College of Law.",
# image: "brown/speakers/Alejandra-Castillo.jpg")
# Speaker.create!(name: "Cid Wilson", description: "Cid Wilson has worked in the financial services industry since 1993. In 2006, Forbes ranked Wilson #1 equity financial analyst for the annual ranking of the Best Wall Street Financial Analysts in the country. He is the Senior Equity Research Analyst for Cabrera Capital Markets LLC in NYC. He serves on the Ethnic Advisory Board for PepsiCo Inc. and the Consumer Advisory Board for Verizon Communications. In 2009, President Barack Obama appointed Wilson to serve on the National Museum of the American Latino Commission with the mission of presenting a plan to the President and Congress on the proposed creation and construction of a new Smithsonian Museum on the National Mall in Washington, DC that would be dedicated to the 500 years of history of Latinos in U.S. Wilson serves on the boards of directors of Latino Justice PRLDEF since 2005, the National Council of La Raza since 2008, and Dominicans On Wall Street since its founding. He is a “Gold Life Member” of the NAACP. As a national Dominican Afro-Latino activist, he is a regular speaker at national conferences around the U.S. discussing issues that impact Latinos of African ancestry. He is a graduate of The Ohio State University. He is a lifelong resident of Bergen County, NJ having attended both public schools and Catholic school in Bergen County.",
# image: "brown/speakers/Cid-Wilson.jpg")
# Speaker.create!(name: "Sergio Marrero", description: "Sergio's interests lie in creating, growing, and developing innovations to revolutionize education. He is co-founding a national network called USAdelante to provide a support network for students in college and prepare the next generation of Latino leaders. Sergio graduated from Northeastern University's College of Engineering in 2007. He participated in the co-op program working in manufacturing at Gillette, Johnson & Johnson, and Procter & Gamble. After graduation he was a supply chain associate in a Gatorade manufacturing facility, a consultant in Deloitte's Strategy & Operations group, and most recently an Education Pioneers Fellow in Teach For America's Strategy and Innovation group. Currently he is a candidate in the Masters of Public Policy and Masters of Business Administration program at Harvard University.",
# image: "brown/speakers/Sergio-Marrero.jpg")
# Speaker.create!(name: "Yahaira Núñez", description: "For over three years, Yahaira M. Núñez has worked at Seedco with their Community Entrepreneurship program. Seedco manages a New York City government contract that offers a set of no cost services designed to help start, operate and expand small businesses in New York City. In 2009, she became the founding staff member to the newly established Washington Heights Center and, through her successful work, was promoted to Senior Account Manager in 2011. Ms. Núñez provides personalized coaching to entrepreneurs in order to identify and develop customized strategies to meet their goals. Ms. Núñez has more than a decade of experience in the non-profit sector beginning with her co-op experience at Harvard Medical School where she spent four years managing grants and research for Boston’s Latino community. As Income Development Coordinator for the American Cancer Society’s Brooklyn office, she helped coordinate three major fundraising events that raised $200,000. Ms. Nunez is currently pursuing her MPA at CUNY Baruch College and received her B.A. in International Affairs and Political Science in 2005 from Northeastern University. Ms. Núñez was awarded the La Comunidad Latina en Acción (LaCLA) scholarship in which recipients volunteer with the Boston Latino community. A Brooklyn native and daughter of immigrants, Ms. Núñez is proud of her Dominican heritage.",
# image: "brown/speakers/Yahaira-Nunez.jpg")
# Speaker.create!(name: "Kelvin Quezada", description: "Kelvin Quezada is an Associate in the Investment Banking division of Barclays Capital. He focuses on working with Senior Bankers to advise private equity firms with key strategic issues involving their portfolios of companies and acquisitions. During his time at Barclays, Kelvin has begun to develop a focus on leverage finance. Prior to working at Barclays, Kelvin held a similar role at Lehman Brothers. Kelvin is a 2008 graduate of Dartmouth College with a Major in Economics and Latin American studies. At Dartmouth, Kelvin was the president of La Alianza Latina and founded a Business club focused on increasing the number of Latinos in the Business and Investment Banking industries. Before Dartmouth, Kelvin attended Manhattan Center in New York City, where he emigrated from Santiago, Dominican Republic. As a Barclays employee and a Dartmouth alum, Kelvin has focused on increasing the amount of Latinos, Dominicans specifically, that attend college and work in the corporate world, through dedicated recruiting and mentoring efforts. At Barclays, Kelvin is one of a number of dedicated mentors who focuses on the continued success on the Latino recruiting process at the firm.",
# image: "brown/speakers/Kelvin-Quezada.jpg")

# Speaker.create!(name: "Almeida Jacqueline Toribio", description: "Almeida Jacqueline Toribio (Ph.D., Cornell University 1993) is Professor of Linguistics in the Department of Spanish and Portuguese at the University of Texas. Her scholarly interests reside at the intersection of linguistics and the sociology of language. Her research itinerary in linguistics examines the ways in which the structural facts of contact and rural varieties of Spanish can be brought to bear on issues central to linguistic theorizing, which has proceeded largely by reference to the language knowledge and use of highly literate, monolingual individuals. Of interest are the phonological, morpho-syntactic, and discursive forms that emerge among monolinguals and bilinguals in the absence of literacy and other normative pressures. A second, related line of research in sociology of language is founded on her abiding concern with the contributions of specific language behaviors, attitudes, and dispositions to the understanding of the configurations of communities and societies in which speakers find themselves. Of particular relevance are the ideologies surrounding language maintenance and identity formation in contexts of cultural contact, as in the case of speakers of Spanish language heritage in the United States and persons residing at the border between the Dominican Republic and Haiti. She has co-edited, with Barbara Bullock, The Cambridge Handbook of Linguistic Code-switching and a special issue of Bilingualism: Language and Cognition devoted to bilingual convergence and she has edited a special issue of Lingua highlighting syntactic-theoretical perspectives on code-switching. Her research has been presented in notable journals, including Linguistic Inquiry, Lingua, Bilingualism: Language & Cognition, International Journal of Bilingualism, Spanish in Context, Linguistics, International Journal of the Sociology of Language, Probus, and Revista Internacional de Lingüística Iberoamericana.",
# image: "brown/speakers/Almeida-Toribio.jpg")
# Speaker.create!(name: "Barbara E. Bullock", description: "Barbara E. Bullock (Ph.D. 1991 University of Delaware) is Professor of French Linguistics and Advisor for the Graduate Program in French Linguistics at the University of Texas at Austin. She specializes in the structural properties of the Romance languages in the American diaspora. She is particularly interested in situating linguistic change in its ecological context, examining the productions and perceptions of immigrant, heritage and borderland speakers who have been isolated from the standardizing norms of literacy and education. Her field and laboratory work includes research on French in the U.S., language contact in Hispaniola, and Spanish-English bilingualism in the US. She is the co-editor of The Cambridge Handbook of Linguistic Code-switching and of Formal Aspects of Romance Linguistics and is the author of numerous articles on phonology, bilingualism, language contact, and language change that appear in important journals and compendia, among these, The French Review, The Journal of French Language Studies, Lingua, Probus, Bilingualism: Language & Cognition, International Journal of Bilingualism, and Revista Internacional de Lingüística Iberoamericana , Rivista di Linguistica, Cahiers Linguistiques d’Ottawa. She serves as Assistant Editor for The French Review and is an active participant in other professional forums that inform her work, including the Linguistic Symposium on Romance Languages, the International Symposium on Bilingualism, the Kentucky Foreign Language Conference, the Hispanic Linguistics Symposium, and the Linguistic Society of America. Her teaching portfolio includes undergraduate courses and graduate seminars in general and French linguistics, including Introduction to Language, History of French, Romance Phonology, Bilingualism, and Language Contact.",
# image: "brown/speakers/Barbara-Bullock.jpg")
# Speaker.create!(name: "Diogenes Abréu", description: "Diógenes Abréu was born in Miches, Dominican Republic. He has studied art at the National School of Fine Arts in Santo Domingo, SUNY, and earned his MFA from City College. In addition to being an artist, Abréu is also a writer and photographer. He has published the following poetry books: POEMS FOR THE LIVING, 1983; and FOR WOMEN WITHOUT MAKE-UP, 1985. Some of his short stories and poems have been published in English, Japanese, and Spanish in compilations and anthologies. His artwork has been exhibited in national as well as international galleries and museums, like the Museum of Modern Art in the Dominican Republic, The New Museum for Contemporary Art in New York, the Queens Museum of Art, and the Metropolitan Museum of Tokyo, Japan. Abréu also worked in theater for more than eight years in his native country and in New York City. In 1998 he won the first prize in the V Short Stories Contest organized by Radio Santa María in the República Dominicana. He was a founding member of Palabra: Expresión Cultural (PEC), a writers’ group dedicated to the development and promotion of Dominican culture in the US. In 2004 he published his book PEREJIL, el ocaso de la “hispanidad” dominicana, a book about Dominican culture and identity viewed from the perspective of the Dominican immigration experience. In 2005, he publisher A PESAR DEL NAUFRAGIO, violencia doméstica y el ejercicio del poder, a book about domestic violence that includes the testimonies of two Dominican women from Washington Heights. His more recent book, released in 2007, is called Engañifas, discurso y práctica social, a critical analysis of the intellectual discourse and social actions of several prominent Dominican personalities. He is currently a founding member of the Dominican-American Visual Artists Collective (CAVDA) in New York.",
# image: "brown/speakers/Diogenes-Abreu.jpg")